[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environment]
NODE_ENV = "production"
PORT = "8080"

[[services]]
name = "pixelbuddy-backend"
source = "."